### ISSUE TITLE
Is it possible to use Nested2Find with CMS content

### ISSUE THREAD

**Issue by ghost** [x2find/Nested2Find#6]
Hi, first congratulations on a great library! Is it possible to integrate Nested2Find with EPiServer CMS (I'm using v8.8)? I've tried calling Client.CreateFromConfig().Conventions.AddNestedConventions(); in Global.asax.cs but the indexed IContent in Find doesn't have the naming convention applied and so any filters when searching Find result in Bad Request responses because the property names haved been modified to the convention. Any ideas please? Sorry to raise this as an issue when it isn't but I didn't want to direct email you. Thanks.

**Comment by pecke01** [comment]
Hi Scott,

I can probably answer that. 

You probably want to do something like this

``` javascript
SearchClient.Instance.Conventions.AddNestedConventions();
```

Since the cms will use the singleton already created when indexing and handling content

**Comment by ghost** [comment]
I just discovered that! Thank you very much.
